In [1]:
import pandas as pd

In [2]:
# Read CSV file
df = pd.read_csv('E:\\CS-6400-Database\\Data\\assigned.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\CS-6400-Database\\Demo Data\\assigned.csv'

In [ ]:
df.head()

   employeeID districts_assigned
0       98839        1,2,3,4,5,6
1      391898                1,4
2      499489        1,2,3,4,5,6
3      658533        1,2,3,4,5,6
4      793035                5,6

In [ ]:
# Split the 'CategoryName' by commas and explode the DataFrame
df = df.assign(districts_assigned=df['districts_assigned'].str.split(',')).explode('districts_assigned')

In [ ]:
# Remove leading/trailing whitespace from 'CategoryName'
df['districts_assigned'] = df['districts_assigned'].str.strip()

In [ ]:
# Display the reformatted DataFrame
print(df.head(10))

   employeeID districts_assigned
0       98839                  1
0       98839                  2
0       98839                  3
0       98839                  4
0       98839                  5
0       98839                  6
1      391898                  1
1      391898                  4
2      499489                  1
2      499489                  2

In [ ]:
df.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_assigned.csv', index=False)

In [ ]:
df.shape

(198, 2)

Convert Product-Category Table

In [ ]:
# Read CSV file
df_category = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Product - Category.csv')

In [ ]:
df_category.head()

   PID                  CategoryName
0    1                      Computer
1    2  Car Audio,MP3 Player,Speaker
2    3                  Air Purifier
3    4                            CD
4    5                        Camera

In [ ]:
# Split the 'CategoryName' by commas and explode the DataFrame
df_category =df_category.assign(CategoryName=df_category['CategoryName'].str.split(',')).explode('CategoryName')

In [ ]:
# Remove leading/trailing whitespace from 'CategoryName'
df_category['CategoryName'] = df_category['CategoryName'].str.strip()

In [ ]:
df_category.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Product - Category.csv', index=False)

In [ ]:
print(df_category.head(10))

   PID  CategoryName
0    1      Computer
1    2     Car Audio
1    2    MP3 Player
1    2       Speaker
2    3  Air Purifier
3    4            CD
4    5        Camera
5    6          Tool
5    6            TV
6    7         Dryer

# report name

In [ ]:
df_Report_Names = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Report_Names.tsv', sep='\t')

In [ ]:
df_Report_Names.shape

(7, 1)

In [ ]:
df_Report_Names.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Report_Names.csv', index=False)

# category

In [ ]:
df_category = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Category.tsv', sep='\t')

In [ ]:
df_category.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Category.csv', index=False)

# city

In [ ]:
df_City = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\City.tsv', sep='\t')

In [ ]:
df_City.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_City.csv', index=False)

# District

In [ ]:
df_District = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\District.tsv', sep='\t')
df_District.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_District.csv', index=False)

# Manufacturer

In [ ]:
df_Manufacturer = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Manufacturer.tsv', sep='\t')
df_Manufacturer.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Manufacturer.csv', index=False)

# Business Day

In [ ]:
df_Date = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Date.tsv', sep='\t')
df_Date.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Date.csv', index=False)

# store

In [ ]:
df_Store = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Store.tsv', sep='\t', dtype={'StoreNumber': str,'StorePhoneNumber': str})
df_Store.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Store.csv', index=False)

In [ ]:
df_Store.shape

(500, 5)

# USER

In [ ]:
# Specify the columns to read
columns_to_read_user = ['EmployeeID', 'Last4_SSN','FName', 'LName', 'AuditLogFlag']

# Read TSV file with specified columns
df_User = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\User.tsv', sep='\t', usecols=columns_to_read_user,dtype={'EmployeeID': str,'Last4_SSN': str} )

In [ ]:
df_User.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_User.csv', columns=columns_to_read_user, index=False)

In [ ]:
df_User.shape

(51, 5)

# ASSIGNED

In [ ]:
# Specify the columns to read
columns_to_read_assigned = ['EmployeeID', 'DistrictNumber']

# Read TSV file with specified columns
df_assigned = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\User.tsv', sep='\t', usecols=columns_to_read_assigned,dtype={'EmployeeID': str,'DistrictNumber': str} )

In [ ]:
df_assigned.head(5)

  EmployeeID DistrictNumber
0    0098839    1,2,3,4,5,6
1    0391898            1,4
2    0499489    1,2,3,4,5,6
3    0658533    1,2,3,4,5,6
4    0793035            5,6

In [ ]:
# Split the 'DistrictNumber' by commas and explode the DataFrame
df_assigned  = df_assigned.assign(DistrictNumber=df_assigned['DistrictNumber'].str.split(',')).explode('DistrictNumber')

In [ ]:
df_assigned.head(5)

  EmployeeID DistrictNumber
0    0098839              1
0    0098839              2
0    0098839              3
0    0098839              4
0    0098839              5

In [ ]:
df_assigned.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_assigned.csv', index=False)

In [ ]:
df_assigned.shape

(198, 2)

# Holiday

In [ ]:
from datetime import datetime

In [ ]:
df_Holiday = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Holiday.tsv', sep='\t', dtype={'AddedByEID': str},skipinitialspace=True)

In [ ]:
df_Holiday

        HDate                       HName AddedByEID
0  2019-02-18             President's Day    0391898
1  2019-01-21  Martin Luther King Jr. Day    8074558
2  2019-01-01              New Year's Day    6037336
3  2018-02-19             President's Day    5420038
4  2018-01-15  Martin Luther King Jr. Day    5420038
5  2018-01-01              New Year's Day    5420038
6  2017-02-20             President's Day    9509608
7  2017-01-16  Martin Luther King Jr. Day    4062271
8  2017-01-01              New Year's Day    4511102

In [ ]:
df_Holiday.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Holiday.csv',  index=False)

# Audit Log

In [ ]:
# Specify the columns to read
columns_audit_log = ['DateAndTime', 'ReportViewed','EmployeeID']

In [ ]:
df_audit_log = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Audit_log.tsv', sep='\t', dtype={'EmployeeID': str})

In [ ]:
df_audit_log.shape

(458, 3)

In [ ]:
df_audit_log['DateAndTime'] = pd.to_datetime(df_audit_log['DateAndTime'], errors='coerce')

In [ ]:
df_audit_log.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_audit_log.csv', columns = columns_audit_log, index=False)

# PRODUCT

In [ ]:
# Specify the columns to read
columns_to_read_product = ['PID', 'PName','RetailPrice','Manufacturer' ]

# Read TSV file with specified columns
df_product = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Product.tsv', sep='\t', usecols=columns_to_read_product,dtype={'PID': str} )

In [ ]:
df_product.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_product.csv', columns = columns_to_read_product, index=False)

# PRODUCT-CATEGORY

In [ ]:
# Specify the columns to read
columns_to_read_PCategory = ['PID', 'CategoryName']

# Read TSV file with specified columns
df_PCategory = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Product.tsv', sep='\t', usecols=columns_to_read_PCategory,dtype={'PID': str} )

In [ ]:
df_PCategory.head()

  PID                  CategoryName
0   1                      Computer
1   2  Car Audio,MP3 Player,Speaker
2   3                  Air Purifier
3   4                            CD
4   5                        Camera

In [ ]:
# Split the 'CategoryName' by commas and explode the DataFrame
df_PCategory  = df_PCategory.assign(CategoryName=df_PCategory['CategoryName'].str.split(',')).explode('CategoryName')

In [ ]:
df_PCategory.head()

  PID  CategoryName
0   1      Computer
1   2     Car Audio
1   2    MP3 Player
1   2       Speaker
2   3  Air Purifier

In [ ]:
df_PCategory.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_PCategory.csv', columns = columns_to_read_PCategory, index=False)

# DISCOUNT

In [4]:
# Specify the columns to read
columns_discount = ['DiscountedDate','DiscountedPrice','PID']

# Read TSV file with specified columns
df_discount = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Discount.tsv', sep='\t', usecols=columns_discount,dtype={'PID': str} )

ValueError: Usecols do not match columns, columns expected but not found: ['DiscountedPrice', 'DiscountedDate']

In [ ]:
df_discount.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_discount.csv', columns = columns_discount, index=False)

In [ ]:
df_discount.shape

(259299, 3)

# Sale

In [ ]:
# Specify the columns to read
columns_sale = ['PID', 'SaleDate','Quantity','StoreNumber' ]

# Read TSV file with specified columns
df_sale = pd.read_csv('E:\\CS-6400-Database\\Demo Data\\Sold.tsv', sep='\t', usecols=columns_sale,dtype={'PID': str, 'StoreNumber': str} )

In [ ]:
df_sale.to_csv('E:\\CS-6400-Database\\Demo Data\\reformatted_Sold.csv', columns = columns_sale, index=True, index_label='SaleID')

In [ ]:
df_sale.shape

(13295, 4)